apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-db
  template:
    metadata:
      labels:
        app: chat-db
    spec:
      containers:
        - args:
            - -c
            - wal_level=logical
            - -p
            - "5433"
          env:
            - name: POSTGRES_DB
              value: chat
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: postgres
          image: postgres:12-alpine
          name: chat-db
          ports:
            - containerPort: 5433
              hostPort: 5433
              protocol: TCP
          volumeMounts:
            - name: chat-vol
              mountPath: /var/lib/postgresql/data
      restartPolicy: Always
      volumes:
        - name: chat-vol
          persistentVolumeClaim:
            claimName: chat-pvc
