apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-db
  template:
    metadata:
      labels:
        app: customer-db
    spec:
      containers:
        - args:
            - -c
            - wal_level=logical
            - -p
            - "5434"
          env:
            - name: POSTGRES_DB
              value: customer
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: postgres
          image: postgres:12-alpine
          name: customer-db
          ports:
            - containerPort: 5434
              hostPort: 5434
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: customer-vol
              mountPath: /var/lib/postgresql/data
      restartPolicy: Always
      volumes:
        - name: customer-vol
          persistentVolumeClaim:
            claimName: customer-pvc
