apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: customer-server-deployment
  name: customer-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-server-service
  strategy: {}
  template:
    metadata:
      labels:
        app: customer-server-service
    spec:
      containers:
        - env:
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: SERVER_PORT
              value: "8020"
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://43.202.52.177:8888
            - name: spring_rabbitmq_host
              value: "43.202.52.177"
            - name: spring_rabbitmq_port
              value: "5672"
            - name: spring_rabbitmq_username
              value: "guest"
            - name: spring_rabbitmq_password
              value: "guest"
            - name: eureka_client_service-url_defaultZone
              value: http://discovery-server-service:8761/eureka
            - name: spring_datasource_hikari_maximum-pool-size
              value: "70"
            - name: spring_datasource_hikari_password
              value: password
            - name: spring_datasource_hikari_username
              value: postgres
            - name: spring_datasource_url
              value: jdbc:postgresql://customer-db:5434/customer
          image: main-service_customer-server:latest
          name: customer-server
          ports:
            - port: 8020
              targetPort: 8020
              protocol: TCP
      restartPolicy: Always
