apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server-service
  template:
    metadata:
      labels:
        app: discovery-server-service
    spec:
      imagePullSecrets:
        - name: ecr-cred
      containers:
        - readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
        - livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
        - resources:
            requests:
              cpu: 0.5
              memory: 0.5Gi
            limits:
              memory: 0.5Gi
        - env:
            - name: spring_rabbitmq_host
              value: "43.202.52.177"
            - name: spring_rabbitmq_port
              value: "5672"
            - name: spring_rabbitmq_username
              value: "guest"
            - name: spring_rabbitmq_password
              value: "guest"
          image: main-service_discovery-server:latest
          name: discovery-server
      restartPolicy: Always
