apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server-service
  template:
    metadata:
      labels:
        app: discovery-server-service
    spec:
      imagePullSecrets:
        - name: ecr-cred
      containers:
      - image: main-service_discovery-server:latest
        name: discovery-server
        env:
          - name: spring_rabbitmq_host
            value: "43.202.52.177"
          - name: spring_rabbitmq_port
            value: "5672"
          - name: spring_rabbitmq_username
            value: "guest"
          - name: spring_rabbitmq_password
            value: "guest"
      restartPolicy: Always
