apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-server-service
  template:
    metadata:
      labels:
        app: front-server-service
    spec:
      imagePullSecrets:
        - name: ecr-cred
      containers:
        - env:
            - name: SERVER_PORT
              value: "8080"
            - name: backend_api_gateway
              value: http://api-server-service:8000
            - name: spring_profiles_active
              value: local
          image: main-service_front-server:latest
          name: front-server-service
      restartPolicy: Always
