apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka1-service
  template:
    spec:
      containers:
        - env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: EXTERNAL://localhost:8097,INTERNAL://kafka1-service:9092
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: INTERNAL
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-service:2181
          image: confluentinc/cp-kafka:7.2.1
          name: kafka1
          ports:
            - containerPort: 9092
              hostPort: 8097
              protocol: TCP
      restartPolicy: Always
