apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-db
  template:
    metadata:
      labels:
        app: customer-db
    spec:
      initContainers:
        - name: init-data-dir
          image: busybox
          command: ["sh", "-c", "mkdir -p /var/lib/postgresql/production/data"]
          volumeMounts:
            - name: chat-vol
              mountPath: /var/lib/postgresql/production/data
      containers:
        - args:
            - -c
            - wal_level=logical
            - -p
            - "5434"
          env:
            - name: POSTGRES_DB
              value: customer
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: user-db-password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: user-db-username
          image: postgres:12-alpine
          name: customer-db
          ports:
            - containerPort: 5434
              hostPort: 5434
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: customer-vol
              mountPath: /var/lib/postgresql/production/data
      restartPolicy: Always
      volumes:
        - name: customer-vol
          persistentVolumeClaim:
            claimName: customer-pvc
