apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      initContainers:
        - name: init-data-dir
          image: busybox
          command: ["sh", "-c", "mkdir -p /data/pgadmin"]
          volumeMounts:
            - name: pgadmin-vol
              mountPath: /data/pgadmin
      containers:
        - name: pgadmin
          image: dpage/pgadmin4
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_CONFIG_PROXY_X_FOR_COUNT
              value: "1"
            - name: PGADMIN_CONFIG_PROXY_X_PROTO_COUNT
              value: "1"
            - name: PGADMIN_CONFIG_PROXY_X_HOST_COUNT
              value: "1"
            - name: PGADMIN_CONFIG_PROXY_X_PORT_COUNT
              value: "1"
            - name: PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT
              value: "1"
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: pgadmin-email
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: pgadmin-password
          volumeMounts:
            - name: pgadmin-vol
              mountPath: /data/pgadmin
      restartPolicy: Always
      volumes:
        - name: pgadmin-vol
          persistentVolumeClaim:
            claimName: pgadmin-pvc