apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-server-service
  template:
    metadata:
      labels:
        app: user-server-service
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - env:
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: spring_kafka_bootstrap-servers
              value: "kafka-service:9092"
            - name: SERVER_PORT
              value: "8010"
            - name: SPRING_MAIN_web-application-type
              value: "reactive"
            - name: eureka_client_service-url_defaultZone
              value: http://discovery-server-service:8761/eureka
            - name: server_undertow_no-request-timeout
              value: "100"
            - name: spring_datasource_hikari_maximum-pool-size
              value: "30"
            - name: spring_datasource_hikari_password
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: user-db-password
            - name: spring_datasource_hikari_username
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: user-db-username
            - name: token_secret
              valueFrom:
                secretKeyRef:
                  name: token-secret
                  key: token-priv-key-64bit
            - name: token_refresh_expiration_time
            - name: token_expiration_time
              valueFrom:
                secretKeyRef:
                  name: token-secret
                  key: token-expiration-time
            - name: token_refresh_expiration_time
              valueFrom:
                secretKeyRef:
                  name: token-secret
                  key: token-refresh-expiration-time
            - name: spring_datasource_hikari_password
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: chat-db-password
            - name: spring_datasource_url
              value: "jdbc:postgresql://user-db:5435/user"
            - name: spring_data_redis_host
              value: "redis-service"
            - name: spring_data_redis_port
              value: "6379"
          image: main-service_user-server:latest
          name: user-server
      restartPolicy: Always