apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
        - args:
            - -c
            - wal_level=logical
            - -p
            - "5435"
          env:
            - name: POSTGRES_DB
              value: user
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: postgres
          image: postgres:12-alpine
          name: user-db
          ports:
            - containerPort: 5435
              hostPort: 5435
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: user-vol
              mountPath: /var/lib/postgresql/data
      restartPolicy: Always
      volumes:
        - name: user-vol
          persistentVolumeClaim:
            claimName: user-pvc