apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-server-service
  template:
    metadata:
      labels:
        app: user-server
    spec:
      containers:
        - env:
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: SERVER_PORT
              value: "8010"
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://43.202.52.177:8888
            - name: SPRING_MAIN_web-application-type
              value: reactive
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: eureka_client_service-url_defaultZone
              value: http://discovery-server-service:8761/eureka
            - name: server_undertow_no-request-timeout
              value: "100"
            - name: spring_datasource_hikari_maximum-pool-size
              value: "30"
            - name: spring_datasource_hikari_password
              value: password
            - name: spring_datasource_hikari_username
              value: postgres
            - name: spring_datasource_url
              value: jdbc:postgresql://user-db:5435/user
            - name: spring_redis_host
              value: user-redis-service
            - name: spring_redis_port
              value: "6379"
          image: main-service_user-server:latest
          name: user-server
          ports:
            - port: 8010
              targetPort: 8010
              protocol: TCP
      restartPolicy: Always