apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-server-service
  template:
    metadata:
      labels:
        app: user-server-service
    spec:
      imagePullSecrets:
        - name: ecr-cred
      containers:
        - env:
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: kafka_bootstrap
              value: http://kafka1-service:9092
            - name: SERVER_PORT
              value: "8010"
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://43.202.52.177:8888
            - name: SPRING_MAIN_web-application-type
              value: reactive
            - name: spring_rabbitmq_host
              value: "43.202.52.177"
            - name: spring_rabbitmq_port
              value: "5672"
            - name: spring_rabbitmq_username
              value: "guest"
            - name: spring_rabbitmq_password
              value: "guest"
            - name: eureka_client_service-url_defaultZone
              value: http://discovery-server-service:8761/eureka
            - name: server_undertow_no-request-timeout
              value: "100"
            - name: spring_datasource_hikari_maximum-pool-size
              value: "30"
            - name: spring_datasource_hikari_password
              value: password
            - name: spring_datasource_hikari_username
              value: postgres
            - name: spring_datasource_url
              value: jdbc:postgresql://user-db:5435/user
            - name: spring_redis_host
              value: redis.default.svc.cluster.local
            - name: spring_redis_port
              value: "6379"
          image: main-service_user-server:latest
          name: user-server
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: 1
              memory: 1.0Gi
            limits:
              memory: 1.0Gi
      restartPolicy: Always