apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::305603388825:user/git_actions
      username: git_actions
      groups:
        - system:masters