apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx
spec:
  controller: k8s.io/ingress-nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-api-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: "www.litcodev.com"
      http:
        paths:
          - pathType: Prefix # 443, 80 etc. -> 80 if "/" prefix
            path: "/grafana"
            backend:
              service:
                name: prometheus-grafana
                port:
                  number: 80
          - pathType: Prefix # 443, 80 etc. -> 80 if "/" prefix
            path: "/eureka(/|$)(.*)"
            backend:
              service:
                name: discovery-server-service
                port:
                  number: 8761
          - pathType: Prefix # 443, 80 etc. -> 80 if "/" prefix
            path: "/"
            backend:
              service:
                name: front-server-service
                port:
                  number: 8080

  tls:
    - hosts:
        - www.litcodev.com
      secretName: hwangbogyumin.cert-c4kkt