apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.network/spring-chatting-server-default: "true"
    io.kompose.service: kafdrop
  name: kafdrop
  namespace: default
spec:
  containers:
    - env:
        - name: JVM_OPTS
          value: -Xms16M -Xmx512M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify
        - name: KAFKA_BROKERCONNECT
          value: kafka1:9092
      image: obsidiandynamics/kafdrop
      name: kafdrop
      ports:
        - containerPort: 9000
          hostPort: 9010
          protocol: TCP
      resources: {}
  restartPolicy: Always
status: {}
