spring:
  datasource:
    url: 'jdbc:postgresql://database-1.cyykxhwims2n.ap-northeast-2.rds.amazonaws.com:5432/postgres'
    hikari:
      username: 'postgres'
      password: 'mypassword'

token:
  expiration_time: 86400000
  secret: '{cipher}45939b87daf906ea6bfce17b4c1d9c0feb3910ca3306a09e8f8cd55b6b9e4d5390302e09b7d03ad6d9fe26e603f8d20e4fe8639c6d1f9644895d991c3e9fae9d'
