spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  application:
    name: chat-service
  messages:
    basename: messages,errors
  datasource:
    hikari:
      maximum-pool-size: 5
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        use-new-id-generator-mappings: true
        order_inserts: true
        ddl-auto: create
        format_sql: true
        jdbc:
          time_zone: UTC
          batch_size: 50




#  main:
#    allow-bean-definition-overriding: true


server:
  error:
    include-stacktrace: never
  tomcat:
    accept-count: 1000
    connection-timeout: 10s
    threads:
      max: 1200
    max-connections: 10000
    max-swallow-size: 2MB
  port: 0


eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health, httpexchanges, beans, busrefresh

logging:
  level:
    com.example.shopuserservice.client: DEBUG
    org.springframework.amqp: ERROR
    org.springframework.boot.actuate.amqp: ERROR