spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  application:
    name: chat-service
  messages:
    basename: messages,errors
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        use-new-id-generator-mappings: true
        order_inserts: true
        ddl-auto: validate
        format_sql: false
        jdbc:
          time_zone: UTC
          batch_size: 50
  data:
    redis:
      host: localhost
      port: 6379
#      lettuce:
#        pool:
#          max-active: 8
#          max-idle: 8
#          min-idle: 0
  profiles:
    active: prod
  kafka:
    bootstrap-servers: kafka1:9092

#  main:
#    allow-bean-definition-overriding: true
kafka:
  enabled: true
  broker:
    number: 1

server:
  error:
    include-stacktrace: never
  tomcat:
    accept-count: 100 # default 100
    connection-timeout: 60s # default 60s
    max-connections: 8192 # default 8192 동시에 처리할 수 있는 최대 연결 수
    max-swallow-size: 2MB # default 2MB
    threads:
      max: 150 # default 200
      min-spare: 30 # default 10


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://spring-cloud-kubernetes-discoveryserver/eureka

management:
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include: health, prometheus

logging:
  level:
    chatting.chat: INFO
    org.springframework.amqp: ERROR
    org.springframework.boot.actuate.amqp: ERROR
    org:
      springframework:
        data:
          jpa: INFO
        web: INFO
