#apiVersion: batch/v1
#kind: CronJob
#metadata:
#  name: ecr-token-refresh
#spec:
#  schedule: "*/1 * * * *" # 1분마다 실행하도록 스케줄을 설정합니다.
#  jobTemplate:
#    spec:
#      template:
#        spec:
#          containers:
#            - name: ecr-token-refresh
#              image: amazon/aws-cli:latest # AWS CLI 이미지 사용
#              args:
#                - /bin/sh
#                - -c
#                - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 305603388825.dkr.ecr.ap-northeast-2.amazonaws.com
#                - kubectl create secret generic ecr-cred --from-file=.dockerconfigjson=/root/.docker/config.json --type=kubernetes.io/dockerconfigjson
#              env:
#                - name: AWS_ACCESS_KEY_ID
#                  valueFrom:
#                    secretKeyRef:
#                      name: ecr-cred
#                      key: AWS_ACCESS_KEY_ID
#                - name: AWS_SECRET_ACCESS_KEY
#                  valueFrom:
#                    secretKeyRef:
#                      name: ecr-cred
#                      key: AWS_SECRET_ACCESS_KEY
#          restartPolicy: OnFailure
