apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-redis
  template:
    metadata:
      labels:
        app: user-redis
    spec:
      containers:
        - name: user-redis
          image: redis:latest
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: redis-config
              mountPath: /usr/local/conf/redis.conf
              subPath: redis.conf
          command:
            - "redis-server"
            - "/usr/local/conf/redis.conf"
      volumes:
        - name: redis-data
          hostPath:
            path: /path/to/redis/data # 호스트의 Redis 데이터 디렉토리 경로로 변경하세요
        - name: redis-config
          configMap:
            name: redis-config-map # 필요한 경우 ConfigMap을 생성하여 설정 파일을 제공할 수 있습니다.
---
apiVersion: v1
kind: Service
metadata:
  name: user-redis-service
spec:
  selector:
    app: user-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 30004
  type: ClusterIP