apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: chatting-server-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chatting-server-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30 # 원하는 CPU 사용률 목표 (30%)
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 1800 # 스케일 다운하기 전 대기 시간 (30분)
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60 # 매트릭 확인 주기 (60초)
    scaleUp:
      stabilizationWindowSeconds: 60 # 스케일 업하기 전 대기 시간 (60초)
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60