version : '3.7'

services:
  user-test-db:
    container_name: user-test-db
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testuser
    expose:
      - "5439"
    ports:
      - "5439:5439"
    volumes:
      - ./backups:/home/backups
    command: -c wal_level=logical -p 5439
    restart: always
  user-test-redis:
    image: redis:latest
    container_name: user-test-redis
    ports:
      - 6380:6380
    expose:
      - 6380
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    command: redis-server /usr/local/conf/redis.conf