apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-prod.yaml
    kompose.version: 1.31.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: chatting-server
  name: chatting-server-service
  namespace: default
spec:
  ports:
    - name: "8030"
      port: 8030
      targetPort: 8030
  selector:
    io.kompose.service: chatting-server
status:
  loadBalancer: {}
