apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-prod.yaml
    kompose.version: 1.31.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: customer-server
  name: customer-server-service
  namespace: default
spec:
  ports:
    - name: "8020"
      port: 8020
      targetPort: 8020
  selector:
    io.kompose.service: customer-server
status:
  loadBalancer: {}
