apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kafdrop
  name: kafdrop-service
  namespace: default
spec:
  ports:
    - name: "9010"
      port: 9010
      targetPort: 9000
  selector:
    io.kompose.service: kafdrop
status:
  loadBalancer: {}
