apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: user-db
  name: user-db-service
  namespace: default
spec:
  ports:
    - name: "5435"
      port: 5435
      targetPort: 5435
    - name: 5435-tcp
      port: 5435
      targetPort: 5435
  selector:
    io.kompose.service: user-db
status:
  loadBalancer: {}
