apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  labels:
    io.kompose.service: zookeeper
spec:
  ports:
    - port: 2181
      targetPort: 2181
  selector:
    io.kompose.service: zookeeper
