apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-server-service
  name: api-server-service
  namespace: default
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
  selector:
    app: api-server-service
