apiVersion: v1
kind: Service
metadata:
  labels:
    app: chat-db
  name: chat-db
spec:
  ports:
    - name: http
      protocol: TCP
      port: 5433
      targetPort: 5433
      nodePort: 30000
  type: NodePort
  selector:
    app: chat-db
