apiVersion: v1
kind: Service
metadata:
  labels:
    app: chatting-server
  name: chatting-server
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8030
      targetPort: 8030
      nodePort: 8030
  type: NodePort
  selector:
    app: chatting-server
