apiVersion: v1
kind: Service
metadata:
  labels:
    app: chatting-server-service
  name: chatting-server-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8030
      targetPort: 8030
  type: ClusterIP
  selector:
    app: chatting-server-service
