apiVersion: v1
kind: Service
metadata:
  labels:
    app: chatting-server
  name: chatting-server
  namespace: only-chat-namespace
spec:
  ports:
    - name: "8030"
      port: 8030
      targetPort: 8030
  selector:
    app: chatting-server
