apiVersion: v1
kind: Service
metadata:
  labels:
    app: chat-db
  name: chat-db
spec:
  ports:
    - name: chat-db
      protocol: TCP
      port: 5433
      targetPort: 5433
  selector:
    app: chat-db
