apiVersion: v1
kind: Service
metadata:
  labels:
    app: customer-db
  name: customer-db
spec:
  ports:
    - name: customer-db
      protocol: TCP
      port: 5434
      targetPort: 5434
  selector:
    app: customer-db
