apiVersion: v1
kind: Service
metadata:
  labels:
    app: customer-db
  name: customer-db-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 5434
      targetPort: 5434
      nodePort: 30001
  type: NodePort
  selector:
    app: customer-db
