apiVersion: v1
kind: Service
metadata:
  labels:
    app: discovery-server-service
  name: discovery-server-service
spec:
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30014
  type: NodePort
  selector:
    app: discovery-server-service
