apiVersion: v1
kind: Service
metadata:
  labels:
    app: discovery-server-service
  name: discovery-server-service
spec:
  ports:
    - port: 8761
      targetPort: 8761
  type: ClusterIP
  selector:
    app: discovery-server-service
