apiVersion: v1
kind: Service
metadata:
  labels:
    app: front-server
  name: front-server
  namespace: only-chat-namespace
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 8000
  selector:
    app: front-server
