apiVersion: v1
kind: Service
metadata:
  labels:
    app: front-server-service
  name: front-server-service
spec:
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP
  selector:
    app: front-server-service
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx
spec:
  controller: k8s.io/ingress-nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-api-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  rules:
    - host: "litcodev.com"
      http:
        paths:
          - pathType: Prefix # 443, 80 etc. -> 80 if "/" prefix
            path: "/"
            backend:
              service:
                name: front-server-service
                port:
                  number: 80
  tls:
    - hosts:
        - litcodev.com
      secretName: litcodev-api.cert