apiVersion: v1
kind: Service
metadata:
  labels:
    app: front-server-service
  name: front-server-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
  selector:
    app: front-server-service
