apiVersion: v1
kind: Service
metadata:
  labels:
    app: front-server-service
  name: front-server-service
spec:
  selector:
    app: front-server-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP