apiVersion: v1
kind: Service
metadata:
  labels:
    app: front-server
  name: front-server
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 8000
  type: NodePort
  selector:
    app: front-server
