apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-server-service
  name: user-server-service
spec:
  ports:
    - port: 8010
      targetPort: 8010
  selector:
    app: user-server-service
