apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-server-service
  name: user-server-service
  namespace: default
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8010
      targetPort: 8010
  selector:
    app: user-server-service
