apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-db
  name: user-db
spec:
  ports:
    - name: user-db
      protocol: TCP
      port: 5435
      targetPort: 5435
  selector:
    app: user-db
