apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-db
  name: user-db-service
spec:
  ports:
    - name: "5435"
      port: 5435
      targetPort: 5435
    - name: 5435-tcp
      port: 5435
      targetPort: 5435
  selector:
    app: user-db
