apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-db
  name: user-db
spec:
  ports:
    - name: http
      protocol: TCP
      port: 5435
      targetPort: 5435
      nodePort: 30002
  type: NodePort
  selector:
    app: user-db
