apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  labels:
    app: zookeeper-service
spec:
  selector:
    app: zookeeper-service
  ports:
    - port: 2181
      targetPort: 2181
  type: ClusterIP
