# See detail values in https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
# PV volume setting https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#persistent-volumes
global:
  scrape_interval: 15s

grafana:
  enabled: true
  ingress:
    enabled: false
  service:
    type: NodePort
    nodePort: 31000


prometheus:
  enabled: true
  ingress:
    enabled: false
  service:
    type: NodePort
    nodePort: 31001
  serviceMonitor:
    interval: "5s"
  storageSpec:
    volumeClaimTemplate:
      spec:
        storageClassName: prometheus
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
        selector:
          matchLabels:
            app: prometheus-pv
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'spring-cloud-api-gateway'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['api-server-service.default.svc.cluster.local:8000']
      - job_name: 'chatting-server'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'chatting-server-service.default.svc.cluster.local:8030' ]
      - job_name: 'chatting-db-exporter'
        static_configs:
          - targets: [ 'postgres-exporter.default.svc.cluster.local:9187' ]
