global:
  scrape_interval: 15s

grafana:
  enabled: true
  ingress:
    enabled: false
  service:
    type: NodePort
    nodePort: 31000

prometheus:
  enabled: true
  ingress:
    enabled: false
  service:
    type: NodePort
    nodePort: 31001
  serviceMonitor:
    interval: "5s"
  prometheusSpec:
#    storageSpec:
#      # Using PersistentVolumeClaim
#      volumeClaimTemplate:
#        spec:
#          storageClassName: ""
#          accessModes: [ "ReadWriteMany" ] # PV의 accessModes와 일치
#          resources:
#            requests:
#              storage: 2Gi
#          selector:
#            matchLabels:
#              app: grafana-pv
    additionalScrapeConfigs:
      - job_name: 'spring-cloud-api-gateway'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['api-server-service.default.svc.cluster.local:8000']
      - job_name: 'chatting-server'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'chatting-server-service.default.svc.cluster.local:8030' ]
      - job_name: 'chatting-db-exporter'
        static_configs:
          - targets: [ 'postgres-exporter.default.svc.cluster.local:9187' ]
