spring:
  messages:
    basename: 'messages,errors'
  profiles:
    active: local

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%-5level) [ %clr(%t{36}){magenta} ] [ %clr(%logger{36}){cyan} ] - %msg%n'
  level:
    chatting:
      chat: TRACE
    root: INFO

# backend endpoint
backend:
  api:
    gateway: http://127.0.0.1:8000



  # cookie
server:
  servlet:
    session:
      tracking-modes: cookie
  port: 7320


kafka:
  bootstrap-servers: localhost:8097,localhost:8098,localhost:8099
  topic-login-response: login-response



