apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chat-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeName: chat-pv
  resources:
    requests:
      storage: 1Gi
  storageClassName: "chat-gce-pd-1"