apiVersion: v1
kind: PersistentVolume
metadata:
  name: chat-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: db-pd # GCE PD의 이름
    fsType: ext4