apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: customer-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: customer-pv
  storageClassName: "customer-gce-pd-1"