apiVersion: v1
kind: PersistentVolume
metadata:
  name: customer-pv
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain # Reclaim 정책 (Delete, Retain, Recycle 중 선택)
  nfs:
    path: /nfs_shared/pgdata-customer # NFS 서버의 공유 경로
    server: 172.31.8.39
