apiVersion: v1
kind: PersistentVolume
metadata:
  name: customer-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: "customer-gce-pd-1"
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: db-pd-4 # GCE PD의 이름
    fsType: ext4
