apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  labels:
    app: grafana-pv
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain # Reclaim 정책 (Delete, Retain, Recycle 중 선택)
  nfs:
    path: /nfs_shared/grafana # NFS 서버의 공유 경로
    server: 172.31.8.39 # private EC2 NFS server IP