apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: db-pd-2 # GCE PD의 이름
    fsType: ext4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeName: pgadmin-pv
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
