apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain # Reclaim 정책 (Delete, Retain, Recycle 중 선택)
  nfs:
    path: /nfs_shared/pgdata-pgadmin # NFS 서버의 공유 경로
    server: 172.31.15.86

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: customer-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
