apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgdata-chat-pv
spec:
  capacity:
    storage: 100Mi # 요구하는 스토리지 용량과 일치해야 합니다.
  volumeMode: Filesystem # 또는 Block
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # Reclaim 정책 (Delete, Retain, Recycle 중 선택)
  storageClassName: standard # StorageClass 이름
  hostPath:
    path: /var/data # 호스트 머신 경로 (호스트 경로를 변경해야 합니다.)
