apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain # Reclaim 정책 (Delete, Retain, Recycle 중 선택)
  nfs:
    path: /nfs_shared/pgdata-user # NFS 서버의 공유 경로
    server: 172.31.15.86
