apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-prod.yaml
    kompose.version: 1.31.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: api-server
  name: api-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-prod.yaml
        kompose.version: 1.31.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/spring-chatting-server-default: "true"
        io.kompose.service: api-server
    spec:
      containers:
        - env:
            - name: SERVER_PORT
              value: "8000"
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://configuration-server:8888
            - name: SPRING_MAIN_web-application-type
              value: reactive
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: eureka_client_service-url_defaultZone
              value: http://discovery-server:8761/eureka
          image: main-service_api-server:latest
          name: api-server
          ports:
            - containerPort: 8000
              hostPort: 8000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
