apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-prod.yaml
    kompose.version: 1.31.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: configuration-server
  name: configuration-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: configuration-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/spring-chatting-server-default: "true"
        io.kompose.service: configuration-server
    spec:
      containers:
        - env:
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: spring_cloud_config_server_git_uri
              value: https://github.com/ghkdqhrbals/spring-chatting-server
          image: main-service_configuration-server:latest
          name: configuration-server
          ports:
            - containerPort: 8888
              hostPort: 8888
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
