server:
  port: 8761

spring:
  application:
    name: discoveryService # MSA ?? ??? ID

eureka:
  client:
    # true: ? ??? ??? ????? ??? ???? ??? DHT? ???.
    register-with-eureka: false
    fetch-registry: false

management:
  endpoint:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

