server:
  port: 8761

spring:
  application:
    name: discoveryService # MSA ?? ??? ID

eureka:
  client:
    # true: ? ??? ??? ????? ??? ???? ??? DHT? ???.
    register-with-eureka: false
    fetch-registry: false