server:
  port: 8761

spring:
  application:
    name: discoveryService # MSA ?? ??? ID
  jersey:
    servlet:
      load-on-startup:

eureka:
  client:
    # true: ? ??? ??? ????? ??? ???? ??? DHT? ???.
    register-with-eureka: false
    fetch-registry: false