server:
  port: 8761

spring:
  application:
    name: discoveryService # MSA ?? ??? ID

eureka:
  client:
    # true: ? ??? ??? ????? ??? ???? ??? DHT? ???.
    register-with-eureka: false
    fetch-registry: false

management:
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
    jmx:
      exposure:
        include: "health,info"
