name: Daily Commit Messages Summary

on:
  push:
    branches:
      - main

jobs:
  fetch-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch commit messages
        run: |
          git log
          COMMIT_MESSAGES=$(git log --since="2023-12-13 00:00:00" --until="2024-02-13 23:59:59" --pretty=format:"%H %ad %s %an" --date=format:'%H:%M:%S')
          echo "$COMMIT_MESSAGES" > commit_messages.txt

      - name: Read commit messages from file
        run: |
          COMMIT_MESSAGES=$(cat commit_messages.txt)
          echo "::set-output name=commit_messages::$COMMIT_MESSAGES"

      - name: Send Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: 'result'
          custom_payload: |
            {
              "attachments": [
                {
                  "color": '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                  "fields": [
                    {
                      "title": "Today commits",
                      "value": "${{ steps.read-commit-messages.outputs.commit_messages }}",
                      "short": false
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
