name: Daily Commit Messages Summary

on:
  push:
    branches:
      - main

jobs:
  fetch-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch commit messages
        id: read-commit-messages
        run: |
          commit_messages=$(git log --since="2023-12-13 00:00:00" --until="2024-02-13 23:59:59" --pretty=format:"%H %ad %s %an" --date=format:'%H:%M:%S')
          echo "::set-output name=COMMIT_MESSAGES::$commit_messages"

      - name: Split commit messages
        id: split-commit-messages
        run: |
          commit_messages="${{ steps.read-commit-messages.outputs.COMMIT_MESSAGES }}"
          IFS=$'\n' read -r -a COMMIT_MESSAGES_ARRAY <<< "$commit_messages"
          for message in "${COMMIT_MESSAGES_ARRAY[@]}"; do
            echo "::set-output name=COMMIT_MESSAGE::$message"
          done

      - name: Send Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: 'result'
          custom_payload: |
            {
              "attachments": [
                {
                  "color": '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                  "fields": [
                    {
                      "title": "Today commits",
                      "value": "${{ steps.split-commit-messages.outputs.COMMIT_MESSAGES }}",
                      "short": false
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
