name: Daily Commit Messages Summary

#on:
#  schedule:
#    - cron: '59 15 * * *' # 분 시 일 월 요일. UTC +9 매일 23:59 에 실행

on:
  push:
    branches:
      - main
      -
jobs:
  fetch-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch commit messages
        id: read-commit-messages
        run: |
          today=$(date +'%Y-%m-%d')' 00:00:00'
          nextday=$(date -d '+1 day' +'%Y-%m-%d')' 00:00:00'
          commit_messages=$(git log --since="$today" --until="$nextday" --pretty=format:"**%ad** | **msg**: %s | **author**: %an" --date=format:'%H:%M:%S' | sed 's/$/ \\n /' | tr -d '\n')
          echo "COMMIT_MESSAGES=$commit_messages" >> $GITHUB_OUTPUT
      - name: Get today date
        id: today-date
        run: |
          TODAY_ONLY_DATE=$(date +'%Y-%m-%d')
          echo "TODAY_ONLY_DATE set to: $TODAY_ONLY_DATE"
          echo "TODAY_DATE=$TODAY_ONLY_DATE" >> $GITHUB_OUTPUT
          
          echo $commit_messages
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          channel-id: 'C06KUB7FR24'
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "Today's commits",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "##${{ steps.today-date.outputs.TODAY_DATE }} \n ${{ steps.read-commit-messages.outputs.COMMIT_MESSAGES }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN_V2 }}