name: Daily Commit Messages Summary

on:
  push:
    branches:
      - main

jobs:
  fetch-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch commit messages
        id: read-commit-messages
        run: |
          commit_messages=$(git log --since="2023-12-13 00:00:00" --until="2024-02-13 23:59:59" --pretty=format:"%h" --date=format:'%H:%M:%S')
          commit_messages=$(echo "$commit_messages" | tr '\n' ' \n ')
          echo "::set-output name=COMMIT_MESSAGES::$commit_messages"
          
          echo $commit_messages
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          channel-id: 'C06KUB7FR24'
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ steps.read-commit-messages.outputs.COMMIT_MESSAGES }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN_V2 }}

#      - name: Send Slack Notification
#        uses: 8398a7/action-slack@v3
#        with:
#          status: custom
#          fields: 'result'
#          custom_payload: |
#            {
#              "attachments": [
#                {
#                  "color": '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
#                  "fields": [
#                    {
#                      "title": "Today commits",
#                      "value": "${{ steps.read-commit-messages.outputs.COMMIT_MESSAGES }}",
#                      "short": false
#                    }
#                  ]
#                }
#              ]
#            }
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
