server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://spring-cloud-kubernetes-discoveryserver/eureka

spring:
  main:
    web-application-type: reactive
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: dev
  application:
    name:
      apigateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: "SCG Global Filter"
            preLogger: true
            postLogger: true
      routes:
        # 세부기능
        - id: user-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/user/actuator/**
            - Method=GET, POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user(?<segment>/?.*), $\{segment}
        # 로그인
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user(?<segment>/?.*), $\{segment}
        # 회원가입
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
        # 관리자 access
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/admin/**
            - Method=GET, POST
          filters:
            - RewritePath=/user(?<segment>/?.*), $\{segment}
        # 일반 사용자 access
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
            - Method=GET, POST, DELETE
          filters:
            - RemoveRequestHeader=Cookie
        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat/**
            - Method=POST, GET, DELETE
          filters:
            - RewritePath=/chat(?<segment>/?.*), $\{segment}
management:
  endpoints:
    web:
      exposure:
        include: health, httpexchanges, beans, busrefresh
  endpoint:
    health:
      show-details: always
  health:
    probes:
      enabled: true